### ISSUE TITLE
Anti Cheating / Alienated Versions

### ISSUE THREAD

**Issue by logsol** [logsol/Chuck#4]
The fact that this game is open source, will make cheating very easy, you'd just need to:
- download the game source
- add cheating functionality
- compile
- start
- connect to our server 
- play and cheat like a motherfucker

I had this idea to keep alienated versions out:
- Create an .as file, that holds connection information and a SECRET variable
- If you try to login, the server sends you a random phrase, which the client has to modify by the secret and maybe md5 hash it
- Client sends back to the server, which has encoded the phrase itself as well
- Server compares and grants authentication

**Comment by jeena** [comment]
The issue is not that the game is open source, you can do this things if it's closed source too. The problem is you can easily check the compiled as file for the "secret" variable even with a simple online decompiler, try to decompile chuck.swf with http://www.showmycode.com/ and it reveals all your code, even with the same variable names and stuff.

**Comment by logsol** [comment]
Hmm, I see. Damnit, I didn't know these decompilers were so efficient and easily accessible. So theres really no way of doing this? Hm, only if the game host was always us.

**Comment by logsol** [comment]
Apparently there's ways to secure your swf code http://www.dcomsoft.com/
But I suppose it's not a really cool, clean, open-source way of doing stuff; might even reduce performance.

**Comment by jeena** [comment]
I don't think we should put in much effort into this right now, the only way to really fix this is to run everything on the server or use some sophisticated stuff like Punkbuster.

**Comment by logsol** [comment]
I agree
